name: Test in Docker

on:
  workflow_dispatch:
    # run jobs manually
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]
  schedule:
    # Do a nightly run of the tests
    - cron: '0 1 * * *'


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: porepy/extended:latest
      TEST_BRANCH: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Restore cached image (if present).
      - name: Restore Docker image cache
        id: cacheDockerImage
        uses: actions/cache@v4
        with:
          path: docker-image.tar
          key: docker-image-${{ env.DOCKER_IMAGE }}

      - name: Load cached image
        if: steps.cacheDockerImage.outputs.cache-hit == 'true'
        run: docker load -i docker-image.tar

      # This runs unconditionally, even if the image is restored from cache. If so, it
      # compares the local image with the one on dockerhub. If a newer version is
      # available online, it will be downloaded and used.
      - name: Pull image (if missing or outdated)
        run: docker pull $DOCKER_IMAGE

      # Save updated image back into cache. Again, this runs unconditionally for the
      # same reason.
      - name: Save Docker image
        run: docker save $DOCKER_IMAGE -o docker-image.tar

      - name: Run tests inside container
        run: |
          docker run --rm $DOCKER_IMAGE \
            bash -c "
              cd ~/porepy &&
              git pull &&
              cd ~/pp_solvers &&
              git fetch origin $TEST_BRANCH &&
              git checkout $TEST_BRANCH &&
              git pull origin $TEST_BRANCH &&
              pip install -e .  # If a new dependency is listed, and the image is not updated yet.
              pytest -v
            "
